apiVersion: v1
kind: Pod
metadata:
  name: daman-webapp
  namespace: webapp   
spec:
  containers:
  - image: 492401058894.dkr.ecr.us-east-1.amazonaws.com/daman-app-repo:application-202307070303
    name: webapp-v1
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: 10.0.244.7
    - name: DBPORT
      value: "3306"
    - name: DBPWD
      value: db_pass123
    command: ["python3", "app.py"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  imagePullSecrets:
    - name: regcred     
