apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: app-employees
spec:
  selector:
    app: employees
    version: v2
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
