apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset-v1
  labels:
    app: employees
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
      - name: webapp-v1
        image: 492401058894.dkr.ecr.us-east-1.amazonaws.com/daman-app-repo:application-v1.1
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: mysql-service.sqldb.svc.cluster.local
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          value: db_pass123
        command: ["python3", "app.py"]
